

spring:
  sql:
    init:
      platform: h2
      mode: always
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    deferred-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: America/Sao_Paulo
  h2:
    console.enabled: true